config/routes.rb
Shouter::Application.routes.draw do
  root to: 'homes#show', via:  :get
  resource :dashboard, only: [:show]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :shouts, only: [:create, :show]
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :use
  default_scope { order("created_at DESC")}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :shouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  protect_from_forgery
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	def show
		@shout = Shout.new
		@shouts =  []
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	before_filter :check_logged_in_user
	def show
	end

	private

	def check_logged_in_user
		if signed_in?
			redirect_to dashboard_path
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  respond_to :html

  def new
  end

  def create
    user = authenticate_session(session_params)
    sign_in(user) or set_flash_message
    respond_with user, location: root_path
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def set_flash_message
    flash.now.notice = "Invalid username or password"
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
	def show
		@shout = Shout.find(params[:id])
	end

	def create
		shout = current_user.shouts.build(shout_parameters)
		if shout.save
			redirect_to dashboard_path
		else
			flash.alert = "Could not shout."
			redirect_to dashboard_path
		end
	end

	private

	def shout_parameters
		params.require(:shout).permit(:body)
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html

  def show
    @user = User.find(params[:id]) 
    @shouts = @user.shouts
  end

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)
    sign_in(@user)
    respond_with @user, location: root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.erb
<%= form_for @shout do |form| %>
	<%= form.text_field :body, placeholder: 'Shout content here' %>
	<%= form.submit 'Shout!' %>
<% end %>

<%= render @shouts %>

app/views/homes/show.html.erb
Welcome to shouter !

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shouter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
	<% if signed_in? %>
		<%= current_user.username, dashboard_path %>
		<%= link_to 'Sign out', session_path, method: :delete %>
	<% else %>
		<%= link_to 'Sign in', new_session_path %>
		<%= link_to 'Sign up', new_user_path %>
	<% end %>
</div>

<% if alert %>
	<p><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/shouts/_shout.html.erb
<%= div_for shout do %>
	<%= link_to shout.user.username, shot.user %>
	shouted
	<%= shout.body %>
	<%= link_to time_ago_in_words(shout.created_at), shout %>
<% end %>

app/views/shouts/show.html.erb
<%= render @shout %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %> </h1>
<%= render @shouts %>